using UnityEngine;
using System.Collections;

/// <summary>
/// Script de comportement d'un bouton
/// </summary>
public class ButtonScript : MonoBehaviour {
	/// <summary>
	/// True si on veut que l'actionnement se d√©roule OnEnter, false si on veut OnExit
	/// </summary>
    public bool _onEnter = true;
	
	/// <summary>
	/// L'element que le bouton actionne
	/// </summary>
    public GameObject _Element;

	// Use this for initialization
	void Start () {
	}
	
	// Update is called once per frame
	void Update () {
	}
	
	// Trigger pour activer le boutton
	void OnTriggerEnter(Collider collision) {
		if(this._onEnter) {
			this._Element.GetComponent<ElementScript>()._isButtonActivated = true;
		}
	}
	
	// Trigger pour activer le boutton
	void OnTriggerExit(Collider collision) {
		if(! this._onEnter) {
			this._Element.GetComponent<ElementScript>()._isButtonActivated = true;
		}
	}
}
